### ISSUE TITLE
scenario for converting onnx to pytorch

### ISSUE THREAD

**Issue by nbcsm** [ToriML/onnx2pytorch#16]
Nice tool!
But out of curiosity, what will be the scenario to use this tool?
Thanks.

**Comment by calvinmccarter-at-lightmatter** [comment]
One example: converting Tensorflow models to PyTorch using ONNX as the intermediate representation, combining tensorflow-onnx (for exporting from TF) and this repo (for importing into PyTorch).

**Comment by nbcsm** [comment]
I guess it is for training scenario, user wants to port a TF model to PyTorch code, right?

**Comment by calvinmccarter-at-lightmatter** [comment]
Yes, training, or really any kind of neural network transformation performed in PyTorch.

**Comment by nbcsm** [comment]
got it, thanks.
