### ISSUE TITLE
NotImplementedError: Conversion not implemented for op_type=Loop.

### ISSUE THREAD

**Issue by wdh234** [ToriML/onnx2pytorch#17]
please Help

**Comment by calvinmccarter-at-lightmatter** [comment]
@wdh234 - implementation is coming soon! Could you share your ONNX model so I can double-check that it works? (IE, upload to Google Drive, Dropbox, or share the link if it's a publicly available model.)

**Comment by wdh234** [comment]
https://drive.google.com/drive/folders/1qx2pKcV6RtKxtC1vk28V8JvvmRbCa0b6
mars.pb ---->>> mars.onnx --->>> mars.pth

**Comment by calvinmccarter-at-lightmatter** [comment]
@wdh234 -- I just tried your model using my latest PR (https://github.com/ToriML/onnx2pytorch/pull/15) implementing Loop, and it seems to be basically working.
I converted `mars.pb` to `mars.onnx` with the following command:
```CUDA_VISIBLE_DEVICES="" python -m tf2onnx.convert --graphdef mars.pb --opset 13 --output mars.onnx --inputs images:0 --outputs l2_normalize:0```

Then I tested your model with my latest PR (you'll have to clone and `python setup.py develop`). I copied `mars.onnx` into the fixtures directory, and ran `tox`. The `test_onnx2pytorch.py` test fails with `rtol=0.001, atol=1e-05` but the actual differences seem small:
```
E           Max absolute difference: 0.01679373
E           Max relative difference: 14.360942
E            x: array([[-0.041362, -0.057395,  0.039973, -0.049108,  0.07204 ,  0.109843,
E                   -0.084947,  0.061786,  0.023853, -0.034895,  0.034628,  0.064104,
E                   -0.051445,  0.098729, -0.075307, -0.005373,  0.171279, -0.080229,...
E            y: array([[-0.046997, -0.051313,  0.051174, -0.051802,  0.07809 ,  0.126148,
E                   -0.084517,  0.063828,  0.030968, -0.035233,  0.034064,  0.066381,
E                   -0.052831,  0.099099, -0.073596,  0.000601,  0.176261, -0.08088 ,...
```
And the mse is:
```
mse 2.6812043870449997e-05
```

**Comment by wdh234** [comment]
Good Job！Thanks！
