### ISSUE TITLE
NotImplementedError: Conversion not implemented for op_type=And.

### ISSUE THREAD

**Issue by melaanya** [ToriML/onnx2pytorch#3]
Hi, thank you for the amazing work! Are there plans to implement other op_types, like op_type=And, for example?

**Comment by Talmaj** [comment]
Hi, thanks! We are open for pull requests. Examples at https://github.com/onnx/onnx/blob/master/docs/Operators.md#And show the behaviour of the operator. If you decide to do a pull request, please add some tests that verify the same behaviour as these examples.

**Comment by Talmaj** [comment]
I've added the op_type=And, Or and Not 133e497.
