### ISSUE TITLE
ImportError: cannot import name '_LazyBatchNorm' from 'torch.nn.modules.batchnorm' (C:\Users\ayush\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\batchnorm.py)

### ISSUE THREAD

**Issue by ayushmankumar7** [ToriML/onnx2pytorch#36]
Code: from onnx2pytorch import ConvertModel

Error: ImportError: cannot import name '_LazyBatchNorm' from 'torch.nn.modules.batchnorm' (C:\Users\ayush\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\batchnorm.py)

**Comment by calvinmccarter-at-lightmatter** [comment]
This was already fixed in version v0.4.1 of onnx2pytorch (see #23), so you likely have an outdated version.

**Comment by ayushmankumar7** [comment]
Oh.. My bad! Thanks!
