### ISSUE TITLE
Forward pass of Reshape

### ISSUE THREAD

**Issue by calvinmccarter-at-lightmatter** [ToriML/onnx2pytorch#8]
I'm having difficulty understanding what's going on in the forward pass of Reshape. It seems to me that `shape = [x if x != 0 else input.size(i) for i, x in enumerate(shape)]` is exactly what the ONNX spec calls for. Is the additional work being done for correctness purposes, or for speedup purposes?

Deleting the additional code is necessary to get onnx2pytorch to work on the Nvidia BERT-Large model [here](https://zenodo.org/record/3733868#.YImM6H1KilM), so perhaps there should be a flag set during __init__ that controls whether this additional work is performed.

**Comment by Talmaj** [comment]
That is used by our internal library for channel pruning. We remove and change the matrices of the layers. Therefore the output shape of those pruned layers change. Some of the code in onnx2pytorch keeps the information of kept/pruned indices for correct forward pass.
